version: '3.5'
services:
#########################
   debian12-x86:
      build: .
      hostname: debian12-x86
      platform: linux/amd64/v3
      image: git.shihaam.dev/dockerfiles/debian-curl:12
   debian12-arm:
      build: .
      hostname: debian12-arm
      platform: linux/arm64
      image: git.shihaam.dev/dockerfiles/debian-curl:12
