version: '3.5'
services:
#########################
  debian11-x86:
    build: .
    hostname: debian11-x86
    platform: linux/amd64/v3
    image: git.shihaam.dev/dockerfiles/debian-curl:11
  debian11-arm:
    build: .
    hostname: debian11-arm
    platform: linux/arm64
    image: git.shihaam.dev/dockerfiles/debian-curl:11
